# This is an example singleton config for testnet.

# module: site
# portal: wal.app
package: 0x5a0c509a659ba982f91ff1189872b8d528f8c02b5f6285a3931fc4c2869ccc9c
general:
   wallet_env: mainnet
   walrus_context: mainnet # Assumes a Walrus CLI setup with a multi-config containing the "mainnet" context.
   # wallet_address: 0x1234...
   # rpc_url: https://fullnode.mainnet.sui.io:443
   # wallet: /path/to/.sui/sui_config/client.yaml
   # walrus_binary: /path/to/walrus
   # walrus_config: /path/to/mainnet/client_config.yaml
   # gas_budget: 500000000
