# This is an example singleton config for testnet.

# module: site
# portal: wal.app
package: 0x22b8c1496650eb45fbcca0f8f37fae77ed33b7d4eaab4da5f0bb9b62a8708dcb
general:
   wallet_env: testnet
   walrus_context: testnet # Assumes a Walrus CLI setup with a multi-config containing the "testnet" context.
   # wallet_address: 0x1234...
   # rpc_url: https://fullnode.testnet.sui.io:443
   # wallet: /path/to/.sui/sui_config/client.yaml
   # walrus_binary: /path/to/walrus
   # walrus_config: /path/to/testnet/client_config.yaml
   # gas_budget: 500000000
