name: "Site Builder Operation"
description: "Run a site-builder command (deploy/update) with cost tracking"

inputs:
  operation:
    description: "Operation to perform: deploy or update"
    required: true
  site_dir:
    description: "Directory containing the site"
    required: true
  output_prefix:
    description: "Prefix for output variables"
    required: true
  epochs:
    description: "Number of epochs"
    required: false
    default: "1"

outputs:
  time:
    description: "Operation duration in seconds"
    value: ${{ steps.run.outputs[format('{0}_time', inputs.output_prefix)] }}
  sui_cost:
    description: "SUI cost in MIST"
    value: ${{ steps.run.outputs[format('{0}_sui_cost', inputs.output_prefix)] }}
  wal_cost:
    description: "WAL cost in units"
    value: ${{ steps.run.outputs[format('{0}_wal_cost', inputs.output_prefix)] }}
  sui_cost_human:
    description: "SUI cost in human readable format"
    value: ${{ steps.run.outputs[format('{0}_sui_cost_human', inputs.output_prefix)] }}
  wal_cost_human:
    description: "WAL cost in human readable format"
    value: ${{ steps.run.outputs[format('{0}_wal_cost_human', inputs.output_prefix)] }}
  site_id:
    description: "Site object ID"
    value: ${{ steps.run.outputs[format('{0}_site_id', inputs.output_prefix)] }}

runs:
  using: "composite"
  steps:
    - name: Run site-builder ${{ inputs.operation }}
      id: run
      shell: bash
      run: |
        ./scripts/site_builder_with_cost.sh \
          --output-prefix "${{ inputs.output_prefix }}" \
          -- ${{ inputs.operation }} "${{ inputs.site_dir }}" --epochs "${{ inputs.epochs }}"
