[package]
name = "walrus_site"
license = "Apache-2.0"
authors = ["Mysten Labs <build@mystenlabs.com>"]
version = "0.0.1"
edition = "2024.beta"

[dependencies]
suins = { r.mvr = "@suins/core" }

[addresses]
walrus_site = "0x0"
