global:
  resolve_timeout: 5m

route:
  group_by: ["alertname"]
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 4h
  receiver: "pagerduty"

receivers:
  - name: "pagerduty"
    pagerduty_configs:
      - service_key: "${{ vars.PAGERDUTY_SERVICE_KEY }}"
        send_resolved: true
