# Gas coin to use and suitable gas budget
gas_coin = "0xc4f78640fe3676fa70368129bf0bde91df2c6fabaf0a7d9f4d94816a9567d91e"
gas_budget = 10_000_000_000

# The Blocksite site package and module where it is published. Defaults to a common
# published package on testnet.
# module = "blocksite"
# package = "0x66b0b2d46dcd2e56952f1bd9e90218deaab0885e0f60ca29163f5e53c72ef810"


# Optional path to sui client config file specifying the network to use and active address. Defaults
# to the sui config in the home directory:
#
# network = "~/.sui/sui_config/client.yaml"
#
# These can alternatively be specified as as a dict with the network name, the wallet address of
# the publisher and a path to the keystore:
#
# [network]
# alias = "local"
# address = "0x962d88830321733c1b25a8f0105e13cb7711a194fd7d0178a453fb26cadc1488"
# [network.keystore]
# file = /Users/jsmith/.sui/sui_config/sui.keystore
