name: deploy vite-react-ts
on:
  workflow_dispatch:
    inputs:
      SUI_NETWORK:
        description: 'Sui network to deploy to'
        required: false
        default: 'mainnet'
      EPOCHS:
        description: 'Epochs to keep the site alive'
        required: false
        default: '5'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'latest'
      - name: Install dependencies
        run: npm install
        working-directory: examples/vite-react-ts
      - name: Build application
        run: npm run build
        working-directory: examples/vite-react-ts
      - name: deploy site
        uses: MystenLabs/walrus-sites/.github/actions/deploy@SEW-154-add-gh-action-to-publish
        with:
          SUI_NETWORK: ${{ inputs.SUI_NETWORK }}
          SUI_ADDRESS: ${{ vars.SUI_ADDRESS_TESTNET }}
          SUI_KEYSTORE: ${{ secrets.SUI_KEYSTORE_TESTNET }}
          DIST_FOLDER: examples/vite-react-ts/dist
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          EPOCHS: ${{ inputs.EPOCHS }}
