name: deploy vite-react-ts
on:
  workflow_dispatch:
    inputs:
      SUI_NETWORK:
        description: 'Sui network to deploy to'
        required: false
        default: 'mainnet'
      EPOCHS:
        description: 'Epochs to keep the site alive'
        required: false
        default: '5'

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Use Node.js
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: 'latest'
      - name: Install dependencies
        run: npm install
        working-directory: examples/vite-react-ts
      - name: Build application
        run: npm run build
        working-directory: examples/vite-react-ts
      - name: deploy site
        uses: MystenLabs/walrus-sites/.github/actions/deploy@3567838a78f974a98d09252ee10f8a237a7a9834
        with:
          SUI_NETWORK: ${{ inputs.SUI_NETWORK }}
          SUI_ADDRESS: ${{ vars.SUI_ADDRESS }}
          SUI_KEYSTORE: ${{ secrets.SUI_KEYSTORE }}
          DIST: examples/vite-react-ts/dist
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          EPOCHS: ${{ inputs.EPOCHS }}
