name: publish snake
on:
  workflow_dispatch
  push:
    branches:
      - 'SEW-154-add-gh-action-to-publish'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: deploy site
        uses: MystenLabs/walrus-sites/.github/actions/publish@SEW-154-add-gh-action-to-publish
        with:
          SUI_NETWORK: testnet
          SUI_ADDRESS: ${{ vars.SUI_ADDRESS_TESTNET }}
          SUI_KEYSTORE: ${{ secrets.SUI_KEYSTORE_TESTNET }}
          DIST_FOLDER: examples/snake
          EPOCHS: 1
