# Tags a specified commit with a given tag name.
# Triggers: Manually via workflow_dispatch, Automatically on repository_dispatch.

name: Tag Site Builder Branch

on:
    repository_dispatch:
        types: [tag-walrus-sites-branch]

    workflow_call:
        inputs:
            walrus_sites_commit:
                description: "Walrus Sites repo commit to tag"
                type: string
                required: true
            tag_name:
                description: "Tag Name"
                type: string
                required: true
    workflow_dispatch:
        inputs:
            walrus_sites_commit:
                description: "Walrus Sites repo commit to tag"
                type: string
                required: true
            tag_name:
                description: "Tag Name"
                type: string
                required: true

env:
    WALRUS_SITES_COMMIT: "${{ github.event.client_payload.walrus_sites_commit || inputs.walrus_sites_commit }}"
    TAG_NAME: "${{ github.event.client_payload.tag_name || inputs.tag_name }}"

jobs:
    tag:
        name: Tag
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # Pin v4.1.1

            - name: Tag
              uses: julbme/gh-action-manage-tag@v1
              with:
                  name: ${{ env.TAG_NAME }}
                  state: present
                  from: ${{ env.WALRUS_SITES_COMMIT }}
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
