name: Tag Walrus-sites Branch

on:
  repository_dispatch:
    types: [tag-walrus-sites-branch]

  workflow_call:
    inputs:
      commit:
        description: 'Walrus-sites repo commit to tag'
        type: string
        required: true
      tag_name:
        description: 'Tag Name'
        type: string
        required: true
  workflow_dispatch:
    inputs:
      commit:
        description: 'Walrus-sites repo commit to tag'
        type: string
        required: true
      tag_name:
        description: 'Tag Name'
        type: string
        required: true

env:
  COMMIT: "${{ github.event.client_payload.commit || inputs.commit }}"
  TAG_NAME: "${{ github.event.client_payload.tag_name || inputs.tag_name }}"

jobs:
  tag:
    name: Tag
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # Pin v4.1.1

      - name: Tag
        uses: julbme/gh-action-manage-tag@8daf6387badea2c6b8f989bd0f82b5a9ef1d84e6 # v1.0.1
        with:
          name: ${{ env.TAG_NAME }}
          state: present
          from: ${{ env.COMMIT }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
